package pl.edu.agh.soa.lab;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.10
 * 2021-04-28T10:26:03.073+02:00
 * Generated source version: 3.3.10
 *
 */
@WebServiceClient(name = "StudentDataService",
                  wsdlLocation = "http://localhost:8080/lab1-example-ejb/StudentData?wsdl",
                  targetNamespace = "http://lab.soa.agh.edu.pl/")
public class StudentDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://lab.soa.agh.edu.pl/", "StudentDataService");
    public final static QName StudentDataPort = new QName("http://lab.soa.agh.edu.pl/", "StudentDataPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/lab1-example-ejb/StudentData?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentDataService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/lab1-example-ejb/StudentData?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentDataService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentDataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentDataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentDataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentData
     */
    @WebEndpoint(name = "StudentDataPort")
    public StudentData getStudentDataPort() {
        return super.getPort(StudentDataPort, StudentData.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentData
     */
    @WebEndpoint(name = "StudentDataPort")
    public StudentData getStudentDataPort(WebServiceFeature... features) {
        return super.getPort(StudentDataPort, StudentData.class, features);
    }

}
